
spring:
  datasource:
    url: jdbc:mysql://ec2-52-79-241-6.ap-northeast-2.compute.amazonaws.com:3306/VTW
    username: root
    password: sa
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
      host: localhost
      port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: immediate
  mail:
    host: smtp.gmail.com
    port: 587
    username:  ${MAIL_USERNAME}
    password:  ${MAIL_PWD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

mybatis:
    mapper-locations: classpath*:mybatis/**/*-mapper.xml
